name: Mystery Message CI #optional, describes what the workflow is about

on: #required, setups the events to be recored in the repo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: #list of actions triggred by the evnts
  build:

    runs-on: ubuntu-latest #clarifies the type of virtual machine to be created by github to run the tests

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps: #steps to run
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run dev
    - run: npm run build --if-present
    - run: npm test
